from __future__ import annotations

import json
import threading
from http.server import ThreadingHTTPServer
from urllib.request import Request, urlopen

from blue_waves.application import BlueWavesApplication
from blue_waves.config import Settings
from blue_waves.service import BlueWavesHandler


def _request(base_url: str, path: str, method: str = "GET", payload: dict | None = None) -> dict:
    body = json.dumps(payload).encode() if payload is not None else None
    request = Request(base_url + path, data=body, method=method, headers={"Content-Type": "application/json"})
    with urlopen(request, timeout=30) as response:
        return json.loads(response.read())


def test_real_cockpit_generation_rejection_retry_approval_and_preview(tmp_path):
    """Exercise the production HTTP path with real ffmpeg/WAV generators, not doubles."""
    settings = Settings(data_dir=tmp_path, youtube_upload_enabled=False)
    application = BlueWavesApplication(settings)
    handler = type("E2EBlueWavesHandler", (BlueWavesHandler,), {"application": application})
    server = ThreadingHTTPServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    base_url = f"http://127.0.0.1:{server.server_port}"
    try:
        video = _request(base_url, "/v1/generate/video", "POST", {
            "topic": "real E2E quality control", "prompt": "Educational title card", "duration": 1, "quality": "draft",
        })
        video_id = video["asset_id"]
        assert video["status"] == "awaiting_owner"
        assert (tmp_path / "videos" / f"{video_id}.mp4").stat().st_size > 0

        rejected = _request(base_url, f"/v1/reject/video/{video_id}", "POST", {"reason": "Improve pacing"})
        assert rejected["status"] == "rejected"
        retry = _request(base_url, f"/v1/retry/video/{video_id}", "POST", {
            "enhancement": "Improve pacing and title readability", "quality": "draft",
        })
        assert retry["attempt"] == 2
        assert retry["parent_asset_id"] == video_id
        assert retry["media_manifest"]["enhancement"] == "Improve pacing and title readability"

        approved = _request(base_url, f"/v1/assets/{retry['asset_id']}/approve", "POST", {})
        assert approved["status"] == "approved"
        assert approved["quality_score"] == 1.0

        media_request = Request(base_url + f"/media/video/{retry['asset_id']}")
        with urlopen(media_request, timeout=30) as response:
            assert response.headers["Content-Type"] == "video/mp4"
            assert len(response.read()) > 0

        music = _request(base_url, "/v1/generate/music", "POST", {
            "topic": "real E2E ambient track", "genre": "ambient", "mood": "calm", "duration_seconds": 2, "quality": "free",
        })
        assert music["status"] == "awaiting_owner"
        assert (tmp_path / "music" / f"{music['asset_id']}.wav").stat().st_size > 0

        podcast = _request(base_url, "/v1/generate/podcast", "POST", {
            "topic": "real E2E podcast", "script": "This is generated by the real cockpit path.",
            "host_voice": "en-US-AriaNeural", "duration_seconds": 2, "quality": "free",
        })
        assert podcast["status"] == "awaiting_owner"
        assert (tmp_path / "podcasts" / f"{podcast['asset_id']}.wav").stat().st_size > 0

        approvals = _request(base_url, "/v1/approvals")
        assert any(item["asset_id"] == retry["asset_id"] for item in approvals["ready_to_publish"])
        assert any(item["asset_id"] == video_id for item in approvals["retryable"])
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def test_provider_catalog_activates_key_only_cloud_connectors(tmp_path):
    application = BlueWavesApplication(Settings(data_dir=tmp_path))
    application.save_connection("cerebras", {"api_key": "test-key"})
    application.save_connection("huggingface", {"api_key": "test-key"})
    configured = {entry["id"] for entry in application.provider_registry.catalog() if entry["configured"]}
    assert {"cerebras", "huggingface"}.issubset(configured)
    assert application.provider_registry.get_text_provider("cerebras").model
    assert application.provider_registry.get_text_provider("huggingface").model
